version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  flower:
    image: mher/flower
    container_name: flower
    depends_on:
      - rabbitmq
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mlflow
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlruns:/app/mlruns

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "tasks", "worker", "--loglevel=DEBUG", "--pool=eventlet", "-E"]
    depends_on:
      - rabbitmq
      - mlflow
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
    - mlruns:/app/mlruns


  mlflow:
    build: ./mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/app/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@postgres:5432/mlflow

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8001:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

volumes:
  mlruns:
  pgdata:
