apiVersion: v1
kind: Secret
metadata:
  name: fraud-secrets
  namespace: fraud-detection
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: mlflow
  POSTGRES_DB: mlflow
  PGADMIN_DEFAULT_EMAIL: zioviris@hotmail.com
  PGADMIN_DEFAULT_PASSWORD: Botvinnik
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
